services:
  database:
    image: postgres:latest
    container_name: educonexion-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 294332
      POSTGRES_DB: EduConexion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    image: educonexion:0.1
    container_name: educonexion-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 294332
      DB_NAME: EduConexion
    depends_on:
      - database
    env_file:
      - .env

volumes:
  postgres_data:
